export const DashboardStyles = {
  dashboardMainContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "100vh",
  },
  firstContainer: {
    width: { md: "20%", lg: "20%", xl: "15%" },
    minWidth: { xl: "270px" },
    height: "100%",
    display: { xs: "none", md: "flex" },
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  welcomeText: {
    fontSize: "14px",
    margin: "30px 0 20px 0 ",
  },
  loremText: {
    fontSize: "16px",
    color: "#0089EC",
    fontWeight: "900",
    marginBottom: "10px",
  },
  syoftLogo: {
    height: "50px",
    width: "100px",
    margin: "30px 0 20px 0",
  },
  syoftLogoMobile: {
    display: { xs: "flex", md: "none" },
    height: "30px",
    width: "60px",
    margin: "30px 0 20px 0",
  },
  divider: {
    width: "90%",
    marginBottom: "20px",
  },
  firstInnerContainer: {
    height: "80%",
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "0px 20px",
  },
  rowContainer: {
    display: "flex",
    alignItems: "center",
  },
  icon: {
    color: "#0089EC",
  },
  dashboard: {
    color: "#0089EC",
    fontSize: "25px",
    fontWeight: "900",
    marginLeft: "10px",
  },
  columnContainer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    alignItems: "flex-start",
  },
  button: {
    background: "linear-gradient(to top, #03BBFB,#0096FF)",
    fontSize: "14px",
    textTransform: "none",
    marginTop: "25px",
    width: "220px",
    borderRadius: "6px",
    fontWeight: "900",
  },
  logoutButton: {
    display: { xs: "flex", sm: "none" },
    background: "linear-gradient(to top, #03BBFB,#0096FF)",
    fontSize: "14px",
    textTransform: "none",
    marginTop: "25px",
    width: "100%",
    borderRadius: "6px",
    fontWeight: "900",
  },
  loremContainer: {
    background: "linear-gradient(to top, #03BBFB,#0096FF)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "220px",
    padding: "10px",
    alignItems: "flex-start",
    borderRadius: "14px",
    color: "#fff",
  },
  lorem: {
    fontSize: "14px",
    fontWeight: "900",
  },
  lorem1: {
    fontSize: "25px",
    fontWeight: "900",
  },
  appIcon: {
    marginBottom: "10px",
  },
  secondContainer: {
    width: { xs: "100%", md: "73%", lg: "80%", xl: "85%" },
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    background: "#F9FAFC",
    boxSizing: "border-box",
  },
  secondInnerContainer: {
    width: "95%",

    height: "90%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    background: "#F9FAFC",
    boxSizing: "border-box",
    overflow: "auto scroll",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  secondRowContainer: {
    display: "flex",
    alignItems: "center",
    gap: { sm: "20px", xl: "40px" },
    width: "100%",
    flexWrap: "wrap",
    margin: "30px 0",
  },
  cardContainer: {
    width: { xs: "100%", md: "300px", lg: "300px", xl: "350px" },
    background: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px 0",
    borderRadius: "20px",
    margin: "10px 0",
  },
  cardRowContainer: {
    display: "flex",
    alignItems: "center",
  },
  iconContainer: {
    height: "60px",
    width: "60px",
    borderRadius: "50%",
    background: "#D9EDFD",
    color: "#0089Ec",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  icons: {
    height: "35px",
    width: "35px",
  },
  secondColumnContainer: {
    marginLeft: "20px",
  },
  columnHeading: {
    fontSize: "35px",
    fontWeight: "bold",
  },
  tableContainer: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    background: "#F9FAFC",
    boxSizing: "border-box",
  },
  name: {
    color: "#0089EC",
  },
  menu: {
    display: {
      xs: "flex",
      sm: "none",
      color: "#0089Ec",
      height: "50px",
      width: "50px",
    },
  },
  headerContainer: {
    width: { xs: "100%", md: "95%", lg: "95%", xl: "95%" },
    height: "7vh",
    display: "flex",
    padding: { xs: "0 20px", md: "0px" },
    justifyContent: "space-between",
    alignItems: "center",
    background: "#fff",
    boxSizing: "border-box",
  },
  headerText: {
    fontSize: { xs: "20px", sm: "25px" },
    marginLeft: "5px",
    fontWeight: "900",
  },
  headerRowContainer: {
    width: { md: "70%", lg: "50%", xl: "40%" },
    display: "flex",
    alignItems: "center",
    justifyContent: { xs: "flex-end", sm: "space-between" },
  },
  notification: {
    color: "#0089Ec",
    height: "50px",
    width: "50px",
    display: { xs: "none", md: "flex" },
  },
  headerInput: {
    height: "50px",
    width: "60%",
    padding: "0px 10px",
    background: "#E9F3FB",
    color: "#0089Ec",

    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: "12px",
    display: { xs: "none", md: "flex" },
  },
  inputField: {
    background: "transparent",
    border: "none",

    outline: "none",
    width: "80%",
    "&:hover": {
      border: "none",
      outline: "none",
      width: "80%",
    },
    "::placeholder": {
      color: "#0089EC",
      fontSize: "14px",
    },
  },
  avatarContainer: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
  },
  admin: {
    margin: "0px 5px",
    display: { xs: "none", sm: "flex" },
  },
  arrow: {
    color: "#0089EC",
    display: { xs: "none", sm: "flex" },
  },
  avatar: {
    display: "flex",
  },
  title: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#000",
  },
  profileContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  profileImageContainer: {
    height: "150px",
    width: "150px",
    borderRadius: "50%",
    border: "7px solid #0089Ec",

    position: "relative",
    margin: "20px",
  },
  profileImage: {
    height: "100%",
    width: "100%",
    borderRadius: "50%",
  },
  inputImage: {
    display: "none",
  },
  profileLabel: {
    position: "absolute",
    top: "10px",
    right: "-5px",
    background: "#fff",
    height: "35px",
    width: "35px",
    borderRadius: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#0089Ec",
    cursor: "pointer",
    border: "2px solid #0089Ec",
  },
  tableMainContainer:{ width: "100%" },
  table:{ minWidth: 750 }
};
